export const constants = {
  SAVE_USER: "SAVE_USER",
  FETCH_USER: "FETCH_USER",
  LOGIN_USER: "LOGIN_USER",
  ADMIN_FETCH_USER: "ADMIN_FETCH_USER",
  FETCH_GALLERY: "FETCH_GALLERY",
  FETCH_USER_SUBSCRIPTIONS: "FETCH_SUB",
  FETCH_SUBSCRIPTION_PLANS: "FETCH_SUBS",
};
